# -*- coding: utf-8 -*-
"""Damin_AgglomerativeClustering_1301164074.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1bXVIy9-MWRMDJ88h9S8xL9dMRdP_56MF

**Agglomeratif Clustering**
"""

#masukan library
import numpy as np
import matplotlib.pyplot as plt
import scipy.cluster.hierarchy as sch
from sklearn.datasets import make_blobs

#mengeluarkan dataset
dataset = make_blobs(n_samples=300, 
                     centers=4, 
                     n_features=2, 
                     cluster_std=1.6, 
                     random_state=50) 

points = dataset[0]

#masukan aglglomeratif clustering
from sklearn.cluster import AgglomerativeClustering

#buat dendrogram
dendrogram = sch.dendrogram(sch.linkage(points, method='ward'))

plt.scatter(dataset[0][:,0],dataset[0][:,1])

#melakukan pengelompokan 
hc = AgglomerativeClustering(n_clusters=4, affinity = 'euclidean', linkage='ward')
y_hc =hc.fit_predict(points)

plt.scatter(points[y_hc == 0,0], points[y_hc == 0,1], s=50, color = 'red')
plt.scatter(points[y_hc == 1,0], points[y_hc == 1,1], s=50, color = 'yellow')
plt.scatter(points[y_hc == 2,0], points[y_hc == 2,1], s=50, color = 'gray')
plt.scatter(points[y_hc == 3,0], points[y_hc == 3,1], s=50, color = 'green')

#plt.scatter()